name: ayeenh
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/icons/
     - assets/i18n/



  fonts:
     - family: Rubik
       fonts:
         - asset: assets/fonts/Rubik-Bold.ttf
         - asset: assets/fonts/Rubik-SemiBold.ttf
         - asset: assets/fonts/Rubik-Medium.ttf
         - asset: assets/fonts/Rubik-Regular.ttf
         - asset: assets/fonts/Rubik-Light.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
